/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        navy: {
          50: '#F0F4F8',
          100: '#D9E2EC',
          200: '#BCCCDC',
          300: '#9FB3C8',
          400: '#829AB1',
          500: '#627D98',
          600: 'var(--color-navy-600)',
          700: '#1A3B60',
          800: 'var(--color-navy-800)',
          900: 'var(--color-navy-900)',
        },
        brand: {
          bg: 'var(--color-bg-app)',
          surface: 'var(--color-surface)',
          alt: 'var(--color-surface-alt)',
          border: 'var(--color-border)',
          inputBg: 'var(--color-input-bg)',
          inputBorder: 'var(--color-input-border)',
          text: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          success: 'var(--color-success)',
          successBg: 'var(--color-success-bg)',
          warning: 'var(--color-warning)',
          warningBg: 'var(--color-warning-bg)',
          danger: 'var(--color-danger)',
          dangerBg: 'var(--color-danger-bg)',
          info: 'var(--color-info)',
          infoBg: 'var(--color-info-bg)',
        },
        behance: {
          bg: '#EBF0FE',
          text: '#0B0A0A',
          accent: '#246AFE',
          white: '#FFFFFF'
        },
        medvice: {
          primary: '#1A56DB', // Bright Royal Blue
          bg: '#F8FAFC', // Very light blue/grey
          text: '#1E293B', // Slate 800
          white: '#FFFFFF',
        },
        // MD3 tokens for Elixir Health Care Redesign
        "tertiary": "#34476c",
        "error": "#ba1a1a",
        "secondary-container": "#dce3eb",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dce3eb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#33476b",
        "on-surface": "#151c27",
        "on-secondary-fixed": "#151c22",
        "on-surface-variant": "#424752",
        "surface-container-highest": "#dce2f3",
        "on-secondary-fixed-variant": "#40484e",
        "on-primary-container": "#c8daff",
        "surface-dim": "#d3daea",
        "surface-bright": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "primary-fixed-dim": "#a9c7ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#a9c7ff",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#005eb8",
        "background": "#f9f9ff",
        "tertiary-container": "#4c5f85",
        "on-primary": "#ffffff",
        "surface-container": "#e7eefe",
        "surface-variant": "#dce2f3",
        "on-secondary-container": "#5e656c",
        "surface-container-high": "#e2e8f8",
        "secondary": "#585f66",
        "outline": "#727783",
        "on-background": "#151c27",
        "primary": "#2563EB",
        "on-tertiary-container": "#cadaff",
        "on-tertiary-fixed": "#031b3d",
        "tertiary-fixed-dim": "#b3c7f2",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001b3d",
        "inverse-on-surface": "#ebf1ff",
        "surface-tint": "#005db6",
        "inverse-surface": "#2a313d",
        "surface": "#f9f9ff",
        "outline-variant": "#c2c6d4",
        "secondary-fixed-dim": "#c0c7cf",
        "tertiary-fixed": "#d7e2ff",
        "on-primary-fixed-variant": "#00468c",
        "gold": "#C5A059"
      },
      fontFamily: {
        display: ['Onest', 'sans-serif'],
        sans: ['Onest', 'sans-serif'],
        body: ['Onest', 'sans-serif'],
        onest: ['Onest', 'sans-serif'],
        "label-sm": ["Poppins"],
        "label-md": ["Poppins"],
        "headline-lg-mobile": ["Poppins"],
        "headline-sm": ["Poppins"],
        "headline-md": ["Poppins"],
        "headline-lg": ["Poppins"],
        "body-lg": ["Poppins"],
        "body-md": ["Poppins"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
        xl: "0.5rem",
        full: "0.75rem",
        "DEFAULT": "0.125rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        card: 'var(--shadow-card)',
        md: 'var(--shadow-md)',
        elevated: 'var(--shadow-elevated)',
      },
      backdropBlur: {
        glass: 'var(--glass-blur)',
      }
    },
  },
  plugins: [],
}
