ALTER TABLE pharmacy_prescriptions ADD COLUMN IF NOT EXISTS valid_until TIMESTAMP;
ALTER TABLE pharmacy_prescriptions ADD COLUMN IF NOT EXISTS refills_allowed INT DEFAULT 0;
ALTER TABLE pharmacy_prescriptions ADD COLUMN IF NOT EXISTS refills_remaining INT DEFAULT 0;
ALTER TABLE pharmacy_prescriptions ADD COLUMN IF NOT EXISTS refill_interval_days INT DEFAULT 0;
ALTER TABLE pharmacy_prescriptions ADD COLUMN IF NOT EXISTS doctor_registration_number VARCHAR(255);

ALTER TABLE pharmacy_prescription_items ADD COLUMN IF NOT EXISTS substitution_allowed BOOLEAN DEFAULT FALSE;
ALTER TABLE pharmacy_prescription_items ADD COLUMN IF NOT EXISTS dispensed_medicine_id BIGINT;
ALTER TABLE pharmacy_prescription_items ADD COLUMN IF NOT EXISTS dispensed_medicine_name VARCHAR(255);

ALTER TABLE pharmacy_outbox_events ADD COLUMN IF NOT EXISTS retry_count INT DEFAULT 0;
ALTER TABLE pharmacy_outbox_events ADD COLUMN IF NOT EXISTS last_error TEXT;

ALTER TABLE pharmacy_medicines ADD COLUMN IF NOT EXISTS schedule_category VARCHAR(50) DEFAULT 'NORMAL';

CREATE TABLE IF NOT EXISTS controlled_substance_register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_prescription_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    dispensed_quantity INT NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    doctor_registration_number VARCHAR(255) NOT NULL,
    dispensed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dispensed_by VARCHAR(255) NOT NULL
);
