import re

def convert_to_mysql(sql):
    """Convert PostgreSQL pg_dump output to MySQL 8.0 compatible DDL."""
    
    # ── 1. Remove Postgres session/config commands ──
    pg_set_commands = [
        r'SET statement_timeout = 0;\r?\n',
        r'SET lock_timeout = 0;\r?\n',
        r'SET idle_in_transaction_session_timeout = 0;\r?\n',
        r"SET client_encoding = '.*?';\r?\n",
        r'SET standard_conforming_strings = on;\r?\n',
        r"SELECT pg_catalog\.set_config\(.*?\);\r?\n",
        r'SET check_function_bodies = false;\r?\n',
        r'SET xmloption = content;\r?\n',
        r'SET client_min_messages = warning;\r?\n',
        r'SET row_security = off;\r?\n',
        r"SET default_tablespace = '';\r?\n",
        r'SET default_table_access_method = heap;\r?\n',
    ]
    for pattern in pg_set_commands:
        sql = re.sub(pattern, '', sql)

    # ── 2. Remove OWNER TO statements ──
    sql = re.sub(r'\n?ALTER TABLE [\w.]+ OWNER TO [\w]+;\r?\n', '\n', sql)

    # ── 3. Remove public. schema prefix ──
    sql = sql.replace('public.', '')

    # ── 4. Convert data types ──
    # character varying(N) -> VARCHAR(N)
    sql = re.sub(r'character varying\((\d+)\)', r'VARCHAR(\1)', sql)
    # character varying (no length) -> VARCHAR(255)
    sql = re.sub(r'character varying', 'VARCHAR(255)', sql)
    
    # timestamp(6) without time zone -> DATETIME(6)
    sql = sql.replace('timestamp(6) without time zone', 'DATETIME(6)')
    # timestamp without time zone -> DATETIME
    sql = sql.replace('timestamp without time zone', 'DATETIME')
    
    # numeric -> DECIMAL
    sql = re.sub(r'\bnumeric\b', 'DECIMAL', sql)

    # boolean -> TINYINT(1)  (MySQL doesn't have native BOOLEAN in DDL from pg_dump)
    # Actually MySQL supports BOOLEAN as alias for TINYINT(1), so this is fine as-is

    # ── 5. Convert IDENTITY columns to AUTO_INCREMENT ──
    # Find all tables/columns with IDENTITY
    identity_matches = re.findall(
        r'ALTER TABLE (\w+) ALTER COLUMN (\w+) ADD GENERATED BY DEFAULT AS IDENTITY',
        sql
    )
    
    # Remove the entire ALTER TABLE ... ADD GENERATED BY DEFAULT AS IDENTITY blocks
    # These span multiple lines ending with );
    sql = re.sub(
        r'\n?ALTER TABLE \w+ ALTER COLUMN \w+ ADD GENERATED BY DEFAULT AS IDENTITY \([^)]*\);\r?\n',
        '\n',
        sql
    )
    
    # Add AUTO_INCREMENT to the column definition in the CREATE TABLE
    for table, col in set(identity_matches):
        # Match: CREATE TABLE tablename ( ... col_name bigint NOT NULL
        # We need to find the column definition inside the CREATE TABLE block
        pattern = rf'(CREATE TABLE {table}\s*\([^;]*?)({col}\s+(?:bigint|integer|int)\s+NOT NULL)'
        def add_auto_increment(match):
            return match.group(1) + match.group(2) + ' AUTO_INCREMENT'
        sql = re.sub(pattern, add_auto_increment, sql, count=1, flags=re.DOTALL)

    # ── 6. Remove sequence blocks (MySQL uses AUTO_INCREMENT) ──
    sql = re.sub(r'--[^\n]*SEQUENCE[^\n]*\n--\n\n', '', sql)

    # ── 7. Convert CHECK constraints with ARRAY syntax ──
    def replace_array_check(match):
        constraint_name = match.group(1)
        col_name = match.group(2)
        array_content = match.group(3)
        values = re.findall(r"'([^']+)'", array_content)
        joined = ', '.join([f"'{v}'" for v in values])
        return f"CONSTRAINT {constraint_name} CHECK ({col_name} IN ({joined}))"
    
    sql = re.sub(
        r"CONSTRAINT (\w+) CHECK \(\(\((\w+)\)::text = ANY \(\(ARRAY\[(.*?)\]\)::text\[\]\)\)\)",
        replace_array_check,
        sql
    )

    # ── 8. Remove remaining ::type casts ──
    sql = re.sub(r'::character varying', '', sql)
    sql = re.sub(r'::text', '', sql)

    # ── 9. Clean up Postgres index syntax ──
    sql = re.sub(r'\s+USING btree\s+', ' ', sql)
    
    # ── 10. ALTER TABLE ONLY -> ALTER TABLE ──
    sql = sql.replace('ALTER TABLE ONLY', 'ALTER TABLE')

    # ── 11. Clean up header comments ──
    sql = re.sub(r'--\n-- PostgreSQL database dump\n--', '-- MySQL schema (converted from pg_dump)', sql)
    sql = re.sub(r'-- Dumped from database version.*\n', '', sql)
    sql = re.sub(r'-- Dumped by pg_dump version.*\n', '', sql)

    # ── 12. Clean up excessive blank lines ──
    sql = re.sub(r'\n{4,}', '\n\n\n', sql)

    return sql


if __name__ == '__main__':
    with open('V9__init_inventory_schema.sql', 'r', encoding='utf-8') as f:
        content = f.read()
    
    result = convert_to_mysql(content)
    
    with open('V9__init_inventory_schema.sql', 'w', encoding='utf-8') as f:
        f.write(result)
    
    print("V9 conversion complete.")
