ALTER TABLE operating_hours ADD COLUMN IF NOT EXISTS department_id BIGINT;
ALTER TABLE operating_hours ADD COLUMN IF NOT EXISTS service_id BIGINT;
ALTER TABLE operating_hours ADD COLUMN IF NOT EXISTS doctor_id BIGINT;
ALTER TABLE operating_hours ADD COLUMN IF NOT EXISTS is_closed BOOLEAN DEFAULT FALSE;

ALTER TABLE operating_hours ALTER COLUMN open_time DROP NOT NULL;
ALTER TABLE operating_hours ALTER COLUMN close_time DROP NOT NULL;
