-- V143__doctor_medicine_recommendations_and_canonical_ecommerce.sql
-- Create doctor_medicine_recommendations table and add recommendation_id to ecommerce_order_items

CREATE TABLE IF NOT EXISTS doctor_medicine_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    consultation_id BIGINT,
    prescription_id BIGINT,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    dosage VARCHAR(100),
    frequency VARCHAR(100),
    duration VARCHAR(100),
    route VARCHAR(100),
    instructions TEXT,
    doctor_notes TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'RECOMMENDED',
    branch_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rec_patient FOREIGN KEY (patient_id) REFERENCES patient_profiles(id),
    CONSTRAINT fk_rec_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_profiles(id),
    CONSTRAINT fk_rec_product FOREIGN KEY (product_id) REFERENCES ecommerce_products(id)
);

CREATE INDEX IF NOT EXISTS idx_rec_patient_id ON doctor_medicine_recommendations(patient_id);
CREATE INDEX IF NOT EXISTS idx_rec_doctor_id ON doctor_medicine_recommendations(doctor_id);
CREATE INDEX IF NOT EXISTS idx_rec_product_id ON doctor_medicine_recommendations(product_id);
CREATE INDEX IF NOT EXISTS idx_rec_status ON doctor_medicine_recommendations(status);

-- Add recommendation_id to ecommerce_order_items
ALTER TABLE ecommerce_order_items ADD COLUMN IF NOT EXISTS recommendation_id BIGINT;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_ecom_item_recommendation'
    ) THEN
        ALTER TABLE ecommerce_order_items 
        ADD CONSTRAINT fk_ecom_item_recommendation 
        FOREIGN KEY (recommendation_id) REFERENCES doctor_medicine_recommendations(id);
    END IF;
END $$;
