spring:
  datasource:
    clinic:
      jdbc-url: ${SPRING_DATASOURCE_CLINIC_URL}
      username: ${SPRING_DATASOURCE_CLINIC_USERNAME}
      password: ${SPRING_DATASOURCE_CLINIC_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 30000
        maximum-pool-size: 10
        max-lifetime: 1800000
        keepalive-time: 300000
    pharmacy:
      jdbc-url: ${SPRING_DATASOURCE_PHARMACY_URL}
      username: ${SPRING_DATASOURCE_PHARMACY_USERNAME}
      password: ${SPRING_DATASOURCE_PHARMACY_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 30000
        maximum-pool-size: 10
        max-lifetime: 1800000
        keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
