spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true

ecommerce:
  payment:
    provider: ${PAYMENT_PROVIDER:STRIPE}
    mode: PRODUCTION
    allow-mock: false
