spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
app:
  datasource:
    clinic:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 5
    pharmacy:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 5
