spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
app:
  datasource:
    clinic:
      jdbc-url: jdbc:postgresql://localhost:5432/clinic_jpa
      username: eakhalaivan
      password: ""
      driver-class-name: org.postgresql.Driver
    pharmacy:
      jdbc-url: jdbc:mysql://localhost:3306/pharmacy_db_test
      username: eakhalaivan
      password: ""
      driver-class-name: com.mysql.cj.jdbc.Driver
