spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  flyway:
    enabled: true

ecommerce:
  payment:
    provider: ${PAYMENT_PROVIDER:STRIPE}
    mode: PRODUCTION
    allow-mock: false
